// <auto-generated />
using System;
using BulkyBookWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyBookWeb.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230625203314_AddCategoryToDatabase")]
    partial class AddCategoryToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.5.23280.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyBookWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Close")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDataTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyVolume")
                        .HasColumnType("int");

                    b.Property<double>("Day2Close")
                        .HasColumnType("float");

                    b.Property<double>("Day2Open")
                        .HasColumnType("float");

                    b.Property<double>("Day2Volume")
                        .HasColumnType("float");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<double>("First2HrsHigh")
                        .HasColumnType("float");

                    b.Property<int>("Float")
                        .HasColumnType("int");

                    b.Property<double>("FromOpen10High")
                        .HasColumnType("float");

                    b.Property<double>("FromOpen30High")
                        .HasColumnType("float");

                    b.Property<double>("HighOfDay")
                        .HasColumnType("float");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LowOfDay")
                        .HasColumnType("float");

                    b.Property<int>("MarketCap")
                        .HasColumnType("int");

                    b.Property<double>("MorningLow")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Open")
                        .HasColumnType("float");

                    b.Property<double>("PrecCloseFromOpen")
                        .HasColumnType("float");

                    b.Property<double>("PrecCompleteRange")
                        .HasColumnType("float");

                    b.Property<double>("PrecDay2Open")
                        .HasColumnType("float");

                    b.Property<double>("PrecFromOpen30High")
                        .HasColumnType("float");

                    b.Property<double>("PrecHighOfDay")
                        .HasColumnType("float");

                    b.Property<double>("PrecLowOfDay")
                        .HasColumnType("float");

                    b.Property<double>("PrevClose")
                        .HasColumnType("float");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
